packages:
  # Core dbt utilities (safe, widely adopted)
  - package: dbt-labs/dbt_utils
    version: 1.1.1

  # Optional: date spine, metrics helpers
  - package: dbt-labs/dbt_date
    version: 0.10.0
